// Generated by https://quicktype.io

export interface Heroes {
    id?:               string;
    superhero:        string;
    alter_ego:        string;
    characters:       string;
    first_appearance: string;
    publisher:        Publisher;
    description:      string;
}

export enum Publisher {
    DCComics = "DC-Comics",
    MarvelComics = "Marvel Comics",
    
}
